# Generated by Django 4.2.5 on 2026-08-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menu'),
        ),
        migrations.AddField(
            model_name='permission',
            name='slug',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='type',
            field=models.CharField(choices=[('READ', 'READ'), ('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS')], default='READ', max_length=10),
        ),
    ]
