# Generated by Django 4.2.5 on 2026-10-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_portal_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortalHomeCache',
        ),
    ]
