# Generated by Django 4.2.5 on 2026-10-03 17:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_portal_home_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.property_photo_path),
        ),
        migrations.AlterField(
            model_name='propertyphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.property_thumbnail_path),
        ),
    ]
