# Generated by Django 4.2.5 on 2026-10-03 18:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_property_photo_external'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=8, unique=True)),
                ('street', models.CharField(blank=True, default='', max_length=200)),
                ('complement', models.CharField(blank=True, default='', max_length=200)),
                ('neighborhood', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state_code', models.CharField(blank=True, default='', max_length=2)),
                ('ibge_code', models.CharField(blank=True, default='', max_length=10)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('not_found', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('cep',),
            },
        ),
    ]
