# Generated by Django 4.2.5 on 2026-10-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_property_ad_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrequest',
            name='cache_status',
            field=models.CharField(blank=True, default='', help_text='HIT quando todo o cache público consultado na request acertou, MISS se algum foi ao banco, vazio se não usou cache.', max_length=4),
        ),
        migrations.AddIndex(
            model_name='logrequest',
            index=models.Index(fields=['cache_status'], name='core_logreq_cache_s_cf58cd_idx'),
        ),
    ]
