# Generated by Django 4.2.5 on 2026-10-08 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_logrequest_cache_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlimportrun',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='xmlimportrun',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Executando'), ('SUCCESS', 'Concluída'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelada'), ('SKIPPED', 'Não executada')], default='SUCCESS', max_length=10),
        ),
        migrations.CreateModel(
            name='XmlImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Na fila'), ('RUNNING', 'Executando'), ('CANCELLING', 'Cancelando'), ('CANCELLED', 'Cancelado'), ('SUCCESS', 'Concluído'), ('PARTIAL', 'Concluído com falhas'), ('FAILED', 'Falhou')], default='QUEUED', max_length=12)),
                ('origin', models.CharField(choices=[('MANUAL', 'Painel'), ('CRON', 'Cron'), ('COMMAND', 'Comando')], default='MANUAL', max_length=10)),
                ('scope', models.CharField(choices=[('ALL', 'Todos os anunciantes'), ('SELECTED', 'Anunciantes escolhidos')], default='ALL', max_length=10)),
                ('advertiser_ids', models.JSONField(blank=True, default=list)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('total_advertisers', models.PositiveIntegerField(default=0)),
                ('done', models.PositiveIntegerField(default=0)),
                ('ok', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('cancelled', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('current_advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.advertiser')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='xmlimportrun',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='core.xmlimportbatch'),
        ),
    ]
