# Generated by Django 4.2.5 on 2026-10-09 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_xmlimportrun_error_message_xmlimportrun_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycontactclick',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertycontactclick',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyfee',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyfee',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyphoto',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyphoto',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='propertyphoto',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyview',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyview',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='propertyphoto',
            index=models.Index(fields=['property', 'is_cover', 'sort_order'], name='core_proper_propert_2b2412_idx'),
        ),
    ]
