"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import tempfile
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_ROOT = BASE_DIR / "static"
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

env_path = BASE_DIR / ".env"
load_dotenv(env_path)


def env_bool(name, default=False):
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")


def env_list(name, default=None):
    raw = os.getenv(name)
    if not raw:
        return default or []
    return [item.strip() for item in raw.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY environment variable is required.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", default=False)

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"] if DEBUG else [])

# Railway: o healthcheck do deploy (railway.json -> healthcheckPath) chega com
# Host "healthcheck.railway.app"; sem ele na lista o Django responde 400 e o deploy falha.
if os.getenv("RAILWAY_ENVIRONMENT") and "healthcheck.railway.app" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("healthcheck.railway.app")

AUTH_USER_MODEL = "core.User"

# Nome do projeto. Única fonte de verdade exibida em:
#   - Django Admin (site_header / site_title)
#   - Documentação OpenAPI (drf-spectacular TITLE)
#   - Templates de e-mail (brand name e remetente, quando não sobrescritos)
PROJECT_NAME = os.getenv("PROJECT_NAME", "Project")

# CORS — nunca usar allow-all em produção
CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", default=DEBUG)
CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS", default=[])
CORS_ALLOW_CREDENTIALS = env_bool("CORS_ALLOW_CREDENTIALS", default=False)
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", default=[])

# Application definition

INSTALLED_APPS = [
    "rest_framework.authtoken",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "csp",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "drf_spectacular",
    "django_filters",
    # django-otp: instalado SEMPRE para que os models/migrations existam.
    # A exigência de MFA no admin é controlada por ADMIN_MFA_ENABLED (ver core/admin.py).
    "django_otp",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_static",
    "core",
    "public",
    "advertiser",
    "xml_import",
]

# MFA no Django Admin (django-otp). Quando True, /admin/ usa OTPAdminSite e
# exige TOTP/static token para usuários staff. Quando False, admin padrão.
ADMIN_MFA_ENABLED = env_bool("ADMIN_MFA_ENABLED", default=False)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("JWT_ACCESS_MINUTES", "60"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("JWT_REFRESH_MINUTES", "1440"))),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "core.classes.permission.SafeDefaultPermission",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "core.classes.pagination.StandardPagination",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "PAGE_SIZE": 15,
    # Versionamento por path (/api/v1/, /api/v2/, ...). ``request.version`` fica
    # disponível para a view escolher comportamento por versão.
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": env_list("API_ALLOWED_VERSIONS", default=["v1"]),
    "VERSION_PARAM": "version",
    "COERCE_DECIMAL_TO_STRING": False,
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%S",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("THROTTLE_ANON", "100/min"),
        "user": os.getenv("THROTTLE_USER", "5000/hour"),
        "login": os.getenv("THROTTLE_LOGIN", "15/min"),
        "forgot_password": os.getenv("THROTTLE_FORGOT", "5/hour"),
        "cep": os.getenv("THROTTLE_CEP", "60/hour"),
        "public": os.getenv("THROTTLE_PUBLIC", "600/min"),
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "core.classes.exception_handler.envelope_exception_handler",
}

SPECTACULAR_SETTINGS = {
    "TITLE": os.getenv("API_TITLE", PROJECT_NAME),
    "DESCRIPTION": os.getenv("API_DESCRIPTION", "API documentation"),
    "VERSION": os.getenv("API_VERSION", "1.0.0"),
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
        "displayRequestDuration": True,
    },
    # Schema/docs SEMPRE exigem usuário autenticado e is_staff,
    # inclusive em DEBUG=True. Para acessar localmente:
    #   python manage.py createsuperuser  -> login em /admin/
    "SERVE_PERMISSIONS": ["rest_framework.permissions.IsAdminUser"],
    "SERVE_AUTHENTICATION": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "SECURITY": [{"Bearer": []}],
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "csp.middleware.CSPMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # django-otp: anexa request.user.is_verified(); inerte enquanto ADMIN_MFA_ENABLED=False.
    "django_otp.middleware.OTPMiddleware",
    "core.middleware.CurrentUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.RequestLoggerMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core" / "template_emails"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.mysql"),
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        # Reaproveita a conexão entre requisições: abrir uma nova com o banco remoto custa ~2s.
        "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
        "CONN_HEALTH_CHECKS": env_bool("DB_CONN_HEALTH_CHECKS", default=True),
    }
}

# Banco do portal legado (PHP, MySQL 5.7), somente leitura, usado por `import_legacy`.
# Não entra em DATABASES porque o Django 4.2 recusa MySQL < 8; o comando conecta
# direto com MySQLdb usando estas variáveis.
LEGACY_DB = {
    "host": os.getenv("DB_PORTAL_ANTIGO_HOST", ""),
    "port": int(os.getenv("DB_PORTAL_ANTIGO_PORT", "3306") or 3306),
    "user": os.getenv("DB_PORTAL_ANTIGO_USER", ""),
    "password": os.getenv("DB_PORTAL_ANTIGO_PASSWORD", ""),
    "name": os.getenv("DB_PORTAL_ANTIGO_NAME", ""),
}


# Security headers (ativos quando DEBUG=False)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_REFERRER_POLICY = "same-origin"
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    # O healthcheck do Railway bate direto no container, em HTTP e sem X-Forwarded-Proto;
    # redirecionar para HTTPS faria o deploy falhar.
    SECURE_REDIRECT_EXEMPT = [r"^api/v1/health/$"]


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = os.getenv("LANGUAGE_CODE", "pt-br")

TIME_ZONE = os.getenv("TIME_ZONE", "America/Sao_Paulo")

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [BASE_DIR / "locale"]

LANGUAGES = [
    ("pt-br", "Português (Brasil)"),
    ("en-us", "English (US)"),
    ("es", "Español"),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------------
# Storage: S3 quando AWS_STORAGE_BUCKET_NAME estiver setado; senão local.
# ---------------------------------------------------------------------------
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")

if AWS_STORAGE_BUCKET_NAME:
    # Bucket com "Bucket owner enforced" (ACLs desabilitadas — padrão atual da
    # AWS). Com AWS_DEFAULT_ACL=None o django-storages omite o cabeçalho de ACL
    # no upload; qualquer valor (até "private") faz a AWS rejeitar com
    # AccessControlListNotSupported. Acesso público é feito via bucket policy.
    AWS_DEFAULT_ACL = None
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "sa-east-1")
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = env_bool("AWS_QUERYSTRING_AUTH", default=True)
    AWS_LOCATION = "static"
    DEFAULT_FILE_STORAGE = "config.storage.MediaStorage"
    STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
else:
    # Dev / testes: filesystem local; nada de tentativas de bucket.
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

URL_FORGOT_PASSWORD = os.getenv("URL_FORGOT_PASSWORD")

# ---------------------------------------------------------------------------
# Request logging (RequestLoggerMiddleware -> LogRequest)
# ---------------------------------------------------------------------------
LOG_REQUESTS_ENABLED = env_bool("LOG_REQUESTS_ENABLED", default=True)
LOG_REQUESTS_RETENTION_DAYS = int(os.getenv("LOG_REQUESTS_RETENTION_DAYS", "30"))
LOG_REQUESTS_MAX_BODY = int(os.getenv("LOG_REQUESTS_MAX_BODY", "10000"))
LOG_REQUESTS_PURGE_SCHEDULE = os.getenv("LOG_REQUESTS_PURGE_SCHEDULE", "03:00")
LOG_REQUESTS_EXCLUDE_PATHS = [
    p.strip()
    for p in os.getenv(
        "LOG_REQUESTS_EXCLUDE_PATHS",
        "/admin/,/static/,/media/,/favicon.ico,/api/v1/health,/api/schema,/api/docs,/api/redoc",
    ).split(",")
    if p.strip()
]
LOG_REQUESTS_SKIP_READ_PATHS = env_list("LOG_REQUESTS_SKIP_READ_PATHS", default=[])

# ---------------------------------------------------------------------------
# Auditoria de mudanças em models (CREATE/UPDATE/DELETE -> LogModelChange)
# ---------------------------------------------------------------------------
MODEL_AUDIT_ENABLED = env_bool("MODEL_AUDIT_ENABLED", default=False)
MODEL_AUDIT_RETENTION_DAYS = int(os.getenv("MODEL_AUDIT_RETENTION_DAYS", "30"))
MODEL_AUDIT_PURGE_SCHEDULE = os.getenv("MODEL_AUDIT_PURGE_SCHEDULE", "03:15")
MODEL_AUDIT_MODELS = [
    label.strip()
    for label in os.getenv("MODEL_AUDIT_MODELS", "core.User").split(",")
    if label.strip()
]

# ---------------------------------------------------------------------------
# E-mail transacional — classe de serviço (core/services/email), provedor Brevo
# ---------------------------------------------------------------------------
EMAIL_PROVIDER = os.getenv("EMAIL_PROVIDER", "brevo")
BREVO_API_KEY = os.getenv("BREVO_API_KEY", "")
BREVO_API_URL = os.getenv("BREVO_API_URL", "https://api.brevo.com/v3/smtp/email")
EMAIL_API_TIMEOUT = int(os.getenv("EMAIL_API_TIMEOUT", "10"))

# ---------------------------------------------------------------------------
# Cache das respostas públicas (core/services/public_cache.py).
# Com REDIS_URL (Railway: ${{Redis.REDIS_URL}}; local: túnel ou Redis local) os dois
# aliases vão para o Redis, compartilhado entre containers/workers. O Redis é dividido
# com o trustimovel-api, por isso o KEY_PREFIX "portal". Sem REDIS_URL: dados em memória
# do processo e versões em arquivo local, compartilhado pelos workers do mesmo container.
REDIS_URL = os.getenv("REDIS_URL")

if REDIS_URL:
    _REDIS_OPTIONS = {
        "socket_connect_timeout": 5,
        "socket_timeout": 5,
        "health_check_interval": 30,
        "retry_on_timeout": True,
    }
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": f"{REDIS_URL}/0",
            "KEY_PREFIX": "portal",
            "TIMEOUT": 300,
            "OPTIONS": _REDIS_OPTIONS,
        },
        "cache_versions": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": f"{REDIS_URL}/0",
            "KEY_PREFIX": "portal:versions",
            "TIMEOUT": None,
            "OPTIONS": _REDIS_OPTIONS,
        },
    }
else:
    CACHES = {
        "default": {
            "BACKEND": os.getenv("CACHE_BACKEND", "django.core.cache.backends.locmem.LocMemCache"),
            "LOCATION": os.getenv("CACHE_LOCATION", "portal-api"),
            "TIMEOUT": int(os.getenv("CACHE_DEFAULT_TIMEOUT", "600")),
            "OPTIONS": {"MAX_ENTRIES": int(os.getenv("CACHE_MAX_ENTRIES", "5000"))},
        },
        "cache_versions": {
            "BACKEND": os.getenv("CACHE_VERSIONS_BACKEND", "django.core.cache.backends.filebased.FileBasedCache"),
            "LOCATION": os.getenv("CACHE_VERSIONS_LOCATION", str(Path(tempfile.gettempdir()) / "portal-api-cache-versions")),
            "TIMEOUT": None,
        },
    }
PUBLIC_CACHE_ENABLED = env_bool("PUBLIC_CACHE_ENABLED", default=True)
# Importação XML (app xml_import): janela noturna no horário de Brasília; começa no início
# e não inicia anunciante novo depois do fim (o restante fica para a noite seguinte).
XML_IMPORT_WINDOW_START = os.getenv("XML_IMPORT_WINDOW_START", "01:00")
XML_IMPORT_WINDOW_END = os.getenv("XML_IMPORT_WINDOW_END", "03:00")
XML_IMPORT_DOWNLOAD_TIMEOUT = int(os.getenv("XML_IMPORT_DOWNLOAD_TIMEOUT", "120"))
XML_IMPORT_MAX_MB = int(os.getenv("XML_IMPORT_MAX_MB", "80"))
# Painel e cron rodam a importação em ``manage.py import_xml`` num processo separado, que devolve
# a memória ao terminar. ``false`` volta a rodar em threads do próprio worker (só para depurar).
XML_IMPORT_SUBPROCESS = env_bool("XML_IMPORT_SUBPROCESS", default=True)
# Estatísticas do site (SearchLog, PropertyView) gravadas numa thread de fundo (core/services/deferred_writes.py).
DEFERRED_WRITES_ENABLED = env_bool("DEFERRED_WRITES_ENABLED", default=True)
SITE_REVALIDATE_URL = os.getenv("SITE_REVALIDATE_URL", "")
SITE_REVALIDATE_SECRET = os.getenv("SITE_REVALIDATE_SECRET", "")
SITE_REVALIDATE_TIMEOUT = int(os.getenv("SITE_REVALIDATE_TIMEOUT", "5"))

# CEP — ViaCEP direto, com cache na tabela PostalCode
# ---------------------------------------------------------------------------
VIACEP_URL = os.getenv("VIACEP_URL", "https://viacep.com.br/ws/{cep}/json/")
CEP_API_TIMEOUT = int(os.getenv("CEP_API_TIMEOUT", "10"))
CEP_CACHE_DAYS = int(os.getenv("CEP_CACHE_DAYS", "365"))

EMAIL_SENDER_NAME = os.getenv("EMAIL_SENDER_NAME", PROJECT_NAME)
EMAIL_SENDER_ADDRESS = os.getenv("EMAIL_SENDER_ADDRESS", "no-reply@example.com")

# Logo pública usada nos templates de e-mail. Precisa ser uma URL acessível
# publicamente (CDN, S3 com ACL public-read, etc.).
EMAIL_LOGO_URL = os.getenv("EMAIL_LOGO_URL", "")
EMAIL_BRAND_NAME = os.getenv("EMAIL_BRAND_NAME", EMAIL_SENDER_NAME)
EMAIL_PRIMARY_COLOR = os.getenv("EMAIL_PRIMARY_COLOR", "#111827")
EMAIL_SUPPORT_ADDRESS = os.getenv("EMAIL_SUPPORT_ADDRESS", EMAIL_SENDER_ADDRESS)

# ---------------------------------------------------------------------------
# Fluxo de verificação de e-mail (opt-in)
# ---------------------------------------------------------------------------
# Quando True:
#   * No registro o usuário recebe um código de 6 dígitos por e-mail.
#   * O usuário só é considerado verificado após confirmar via /auth/verify-email/.
#   * O envio de boas-vindas só ocorre APÓS a verificação.
EMAIL_VERIFICATION_REQUIRED = env_bool("EMAIL_VERIFICATION_REQUIRED", default=False)
EMAIL_VERIFICATION_CODE_TTL_MIN = int(os.getenv("EMAIL_VERIFICATION_CODE_TTL_MIN", "30"))


# ---------------------------------------------------------------------------
# Content Security Policy (django-csp v4 usa CONTENT_SECURITY_POLICY)
# ---------------------------------------------------------------------------
_csp_default_src = tuple(env_list("CSP_DEFAULT_SRC", default=["'self'"]))
_csp_script_src = tuple(
    env_list(
        "CSP_SCRIPT_SRC",
        default=[
            "'self'",
            # Swagger UI / Redoc são servidos via CDN do drf-spectacular
            "https://cdn.jsdelivr.net",
            "'unsafe-inline'",
        ],
    )
)
_csp_style_src = tuple(
    env_list(
        "CSP_STYLE_SRC",
        default=[
            "'self'",
            "https://cdn.jsdelivr.net",
            "https://fonts.googleapis.com",
            "'unsafe-inline'",
        ],
    )
)
_csp_font_src = tuple(
    env_list(
        "CSP_FONT_SRC",
        default=[
            "'self'",
            "https://fonts.gstatic.com",
            "data:",
        ],
    )
)
_csp_img_src = tuple(
    env_list(
        "CSP_IMG_SRC",
        default=[
            "'self'",
            "data:",
            "https:",
        ],
    )
)
_csp_connect_src = tuple(env_list("CSP_CONNECT_SRC", default=["'self'"]))

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": _csp_default_src,
        "script-src": _csp_script_src,
        "style-src": _csp_style_src,
        "font-src": _csp_font_src,
        "img-src": _csp_img_src,
        "connect-src": _csp_connect_src,
        "frame-ancestors": ("'none'",),
        "object-src": ("'none'",),
        "base-uri": ("'self'",),
    },
}
